version: 0.2

phases:
  build:
    commands:
      - echo building the application
      - ./gradlew build

artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'